### ISSUE TITLE
Timer.Cancel()

### ISSUE THREAD

**Issue by mirel-maestral** [gurmitteotia/guflow#19]
Is it possible to cancel a Timer from the code?

**Comment by alexzm1** [comment]
I believe the way to cancel a Timer from a Workflow inheriting class is sending the **WorkflowAction** obtained when calling 
`CancelRequest.ForTimer(name: "TimerName")`

The only Issue I have seen doing this is that, the configured Function in method **OnCancelled** of **SchedullerTimer** is not being executed after **Timer Cancellation** via **CancelRequest.ForTimer** method.

I.E.

`SchedulerTimer(name: "TimerName").OnCancelled(_=> //Do Something which will return a WorkflowAction);`

**Comment by alexzm1** [comment]
Here is a code snipped that could help to understand the problem

`
public class TestWorkflow : Workflow {

	//WorkflowDescription setup skiped  

	public TestWorkflow(){

		ScheduleActivity<TrigerTimerActivity>();
		
		ScheduleTimer("TimerTest")
			.AfterActivity<TrigerTimerActivity>()
			.FireAfter(TimeSpan.FromMinutes(2))
			.OnFired(_ =>
				{
					return FailWorkflow("Failed Cancel Timer", "Failed to canel TimerTest");
				})
			.OnCancelled(_ =>
				{
					return CompleteWorkflow("Workflow Execution Completed"); //Not Executed After timer cancellation
				}
			);

	}

	[WorkflowEvent(EventName.Signal)]
	public WorkflowAction OnSignal(WorkflowSignaledEvent @event)
	{
		if ("cancel timer".EqualsIgnoreCase(@event.SignalName))
		{
			return CancelRequest.ForTimer(name: "TimerTest");
		}
	}

}
`

**Comment by gurmitteotia** [comment]
OnCancelled should execute when timer is cancelled. I will have a look.
Meanwhile can you check following things please:

- Make sure in history events that timer is being cancelled. You can login to AWS console to check history events of  a particular workflow
- Check if workflow host is reporting any error. You can log any error as below:
```cs
workflow.OnError(e=>{
  //Or log it
 Console.WriteLine(e.Exception);
return ErrorAction.Continue;
});
```
You can read more about exception handling [here](https://github.com/gurmitteotia/guflow/wiki/Error-handling)

- Put a guard before cancelling the timer. If you try to cancel a timer which is not active than the event will be raised to indicate that cancellation has failed. It will cause the workflow to fail. However you can handle to provide other workflow action:

```cs
public TestWorkflow(){


	ScheduleTimer("TimerTest")
		.AfterActivity<TriggerTimerActivity>()
		.FireAfter(TimeSpan.FromMinutes(2))
		.OnFired(_ =>
			{
				return FailWorkflow("Failed Cancel Timer", "Failed to cancel TimerTest"); //Executed after timer's TimeSpan (2 minutes in this case)
			})
		.OnCancelled(_ =>
			{
				return CompleteWorkflow("Workflow Execution Completed"); //Not Executed After timer cancellation
			}
		).OnCancellationFailed(_=>Provide your custom action);

}

[WorkflowEvent(EventName.Signal)]
public WorkflowAction OnSignal(WorkflowSignaledEvent @event)
{
    
	if ("cancel timer".EqualsIgnoreCase(@event.SignalName))
	{
              if (Timer("TimerTest").IsActive)
                    return CancelRequest.ForTimer("TimerTest");
	}
        return Ignore;
}
```

**Comment by gurmitteotia** [comment]
This is the issue with Amazon SWF. I can see in history event that is timer is cancelled but decision tasks are not scheduled. OnCancelled event will be raised only when decision tasks are scheduled. I will raise this on Amazon's SWF forum.  I have attached the image of history events I saw:
![aws_events](https://user-images.githubusercontent.com/10597526/45641703-21dce280-baae-11e8-89a1-110156dab3bc.png)

**Comment by alexzm1** [comment]
Hi Gurmit!

Just checked and the SWF console is showing the Timer as cancelled in the Events History tab, also I'm not getting any error logged on any of the Workflow Error handlers I've setup (OnError, OnPollingError, OnResponseError or OnFault).

I also setup **OnCancellationFailed** in my timer but it seems that not even that function is being invoked when I cancel the Timer.

**Comment by gurmitteotia** [comment]
I'm raising it on Amazon SWF forum but I doubt we will get a quick answer from there. I think you should use following workaround for now:

```
public TestWorkflow(){


	ScheduleTimer("TimerTest")
		.AfterActivity<TriggerTimerActivity>()
		.FireAfter(TimeSpan.FromMinutes(2))
		.OnFired(_ =>
			{
				return FailWorkflow("Failed Cancel Timer", "Failed to cancel TimerTest"); //Executed after timer's TimeSpan (2 minutes in this case)
			})
		).OnCancellationFailed(_=>Provide your custom action);

}

[WorkflowEvent(EventName.Signal)]
public WorkflowAction OnSignal(WorkflowSignaledEvent @event)
{
    
	if ("cancel timer".EqualsIgnoreCase(@event.SignalName))
	{
              if (Timer("TimerTest").IsActive)
                    return CompleteWorkflow("Workflow Execution Completed");
	}
        return Ignore;
}
```

**Comment by gurmitteotia** [comment]
I have raised it on Amazon SWF https://forums.aws.amazon.com/thread.jspa?threadID=290071&tstart=0

**Comment by alexzm1** [comment]
Got it! n thanks for following up on this.

Also let´s say we have a few more Activities that we were supposed to call after Timer Cancellation, rather than just closing the Workflow like in the previous example, what would you recommend us to do?



`
public class TestWorkflow : Workflow {

	//WorkflowDescription setup skiped  

	public TestWorkflow(){

		ScheduleActivity<TriggerTimerActivity>();
		
		ScheduleTimer("TimerTest")
			.AfterActivity<TriggerTimerActivity>()
			.FireAfter(TimeSpan.FromMinutes(2))
			.OnFired(_ =>
				{
					return FailWorkflow("Failed Cancel Timer", "Failed to cancel TimerTest"); //Executed after timer's TimeSpan (2 minutes in this case)
				})
			.OnCancelled(_ =>
				{
					return Jump.ToActivity<AfterTimerActivity>(); //Not Executed After timer cancellation
				}
			);
		
		ScheduleActivity<AfterTimerActivity>().AfterTimer("TimerTest").OnCompletion(_=>{
			return CompleteWorkflow("Workflow Execution Completed");
		});
		
	}

	[WorkflowEvent(EventName.Signal)]
	public WorkflowAction OnSignal(WorkflowSignaledEvent @event)
	{
		if ("cancel timer".EqualsIgnoreCase(@event.SignalName))
		{
			if (Timer("TimerTest").IsActive)
				return CancelRequest.ForTimer("TimerTest");
		}
        return Ignore;
	}
}
`

**Comment by gurmitteotia** [comment]
In following example OrderCancelled activity is scheduled when timer is cancelled while ShipOrder activity is scheduled when timer is successfully fired. 
```cs
[WorkflowDescription("1.0")]
public class OrderWorkflow : Workflow
{

 public OrderWorkflow()
 {
 
	ScheduleTimer("GracePeriod").FireAfter(TimeSpan.FromMinutes(20));
	
	ScheduleActivity<OrderCancelled>().AfterTimer("GracePeriod)
			.When(_=>Parent(a).LastEvent() is TimerCancelledEvent); // Or simply .When(_=>false)
			
	ScheduleActivity<ShipOrder>().AfterTimer("GracePeriod")
				.When(a=>Parent(a).LastEvent() is TimerFiredEvent);
				
  }
  
  [WorkflowEvent(EventName.Signal)]
  public WorkflowAction OnSignal(WorkflowSignaledEvent @event)
 {
	if ("cancel timer".EqualsIgnoreCase(@event.SignalName))
	{
	    //You can combine multiple workflow actions together
           if (Timer("GracePeriod").IsActive)
			return CancelRequest.ForTimer("GracePeriod") + Jump.ToActivity<OrderCancelled>();
	}
    return Ignore;
 }
}
```
Hope that helps!

**Comment by alexzm1** [comment]
Wow! that's a big surprise, I wasn't expecting to be able to return concatenated **WorkflowActions**.

Again thanks for your help!

**Comment by gurmitteotia** [comment]
Yes, it does you can read more about it [here](https://github.com/gurmitteotia/guflow/wiki/Workflow-actions). Understanding of [Deflow algorithm](https://github.com/gurmitteotia/guflow/wiki/Deflow-algorithm) and [workflow execution](https://github.com/gurmitteotia/guflow/wiki/Execution-branches) will give you a pretty good understanding on workflow is executed.

**Comment by gurmitteotia** [comment]
I will update the Guflow library to align with Amazon SWF. You can find my response [here](https://forums.aws.amazon.com/thread.jspa?threadID=290071&tstart=0). In my opinion it would be better to raise ScheduleDecisionTask event for TimerCancelled event.  I will raise it a feature request if I come to know about the right place to raise it.  Please use the suggested example above. I have updated it to make to more meaningful.

**Comment by alexzm1** [comment]
Will do! Thanks

**Comment by gurmitteotia** [comment]
I'm closing it now as this issue is resolved.
