### ISSUE TITLE
Supports child workflows

### ISSUE THREAD

**Issue by gurmitteotia** [gurmitteotia/guflow#2]
Workflow should allow the scheduling of child workflows.
Child workflows will simplify the writing of complex workflows.
Follow features should make this card complete:
*  Allow scheduling APIs to schedule child workflows
*  Supports query APIs to read child workflows events
*  Child workflow can be scheduled after any other item or vice-versa
*  Allow cancellation of child workflows
*  Allow sending of signals between workflows/child workflows

An example:
```cs
public class BookHolidaysWorkflow : Workflow
{
  public BookHolidaysWorkflow()
  {
      ScheduleChildWorkflow<BookFlight>()
      ScheduleChildWorkflow<BookHotel>().AfterChildWorkflow<BookFlight>();

  }
}
```

**Comment by tholgate330** [comment]
Hello there, I wanted to see if there's any priority for adding support for child workflows in this issue / whether you've got a rough ETA? Thanks!

**Comment by gurmitteotia** [comment]
This is next high priority ticket and it should be out roughly in next 2-3 weeks.

**Comment by tholgate330** [comment]
Appreciate the response! We were considering creating a fork of the library to add this in, but if you're expecting it to be done in October that might fit our timelines. Looking at the commits it appears like you've been maintaining the library on your own since you finished it, are you open to additional contributors helping out?

**Comment by gurmitteotia** [comment]
Yes definitely,  contributions from open source community will enrich this library further. I will soon publish the contributing guidelines in github repository.

**Comment by gurmitteotia** [comment]
Hi, this feature should be out before end of this week.

**Comment by gurmitteotia** [comment]
Version [1.2.7](https://www.nuget.org/packages/Guflow/1.2.7) now fully supports the scheduling of child workflows. I have also written a [sample](https://github.com/gurmitteotia/guflow-samples/tree/master/ChildWorkflow) to demonstrate the scheduling of child workflows and communication between them. I will update the documentation this week. Child workflow APIs are pretty much consistent with activity and lambda APIs.

**Comment by gurmitteotia** [comment]
I have updated the documentation. Closing it now.
