### ISSUE TITLE
Signal child workflows

### ISSUE THREAD

**Issue by alexzm1** [gurmitteotia/guflow#37]
Is there any way to signal child workflows?

Let's say we got the configuration the below configuration

```

[WorkflowDescription("1.0")]
public class OrderWorkflow : Workflow
{
   public OrderWorkflow()
   {  
      ScheduleActivity<CreateOrderActivity>()
         .When(_ => Input.resourceId != null)
         .OnCompletion(_ => Ignore);
      
      ScheduleChildWorkflow<ChargeCustomerWorkflow>().When(_ => Ignore);
   }
   
   [WorkflowEvent(EventName.Signal)]
   public WorkflowAction OnSignal(WorkflowSignaledEvent @event)
   {
      if(@event.SignalName.Equals("child-workflow")){
         return Jump.ToChildWorkflow("charge-customer-workflow", "1.0");
      }
   }
}

[WorkflowDescription("1.0", Name = "charge-customer-workflow")]
public class ChargeCustomerWorkflow : Workflow
{
   public ChargeCustomerWorkflow()
   {
      ScheduleActivity<WaitForBankResponseActivity>();
      ScheduleActivity<AcceptCardDetails>().AfterActivity<WaitForBankResponseActivity>()
      ScheduleActivity<ChargeCustomer>().AfterActivity<AcceptCardDetails>();
   }
}

```

How can we Jump to the execution of **AcceptCardDetails** from a Signal event? I was able to jump to the ChildWorkflow execuion (ChargeCustomerWorkflow), but was not able to jump from [WorkflowEvent(EventName.Signal)] method in the OrderWorkflow in class, I tried adding a [WorkflowEvent(EventName.Signal)] in the ChargeCustomerWorkflow class but was not able to get access to the signal.

Not sure if this is related to this issue 

https://github.com/gurmitteotia/guflow/issues/26

Regards

**Comment by gurmitteotia** [comment]
Both OrderWorkflow and ChargeCustomerWorkflow will have separate execution history. Signalling parent workflow "OrderWorkflow" does not mean it will be sent to child workflow "ChargeCustomerWorkflow" automatically. From the parent workflow, you have to pass the signal to child workflow (make sure child workflow is running) and child workflow you have to handle this signal.

Please look at this [example](https://github.com/gurmitteotia/guflow-samples/tree/master/ChildWorkflow). It shows how to send signals between parent and child workflows.

**Comment by alexzm1** [comment]
Good!

I have another scenario where we may need to send a signal just after the child workflow was executed. I was trying to do something like this

```
[WorkflowDescription("1.0")]
public class OrderWorkflow : Workflow
{
   public OrderWorkflow()
   {  
      ScheduleActivity<CreateOrderActivity>()
         .When(_ => Input.resourceId != null)
         .OnCompletion(_ => Ignore);
      
      ScheduleChildWorkflow<ChargeCustomerWorkflow>().When(_ => Ignore);
   }
   
   [WorkflowEvent(EventName.Signal)]
   public WorkflowAction OnSignal(WorkflowSignaledEvent @event)
   {
      if(@event.SignalName.Equals("WaitForBank") || @event.SignalName.Equals("AcceptCardDetails")){
         return Jump.ToChildWorkflow("charge-customer-workflow", "1.0") + 
         Signal(@event.SignalName, @event.Input).ForChildWorkflow<ChargeCustomerWorkflow>();
      }
     
     return Ignore;
   }
}

[WorkflowDescription("1.0", Name = "charge-customer-workflow")]
public class ChargeCustomerWorkflow : Workflow
{
   public ChargeCustomerWorkflow()
   {
      ScheduleActivity<WaitForBankResponseActivity>().When(_=>false);
      ScheduleActivity<AcceptCardDetails>().When(_=>false)
      ScheduleActivity<ChargeCustomer>()
         .AfterActivity<WaitForBankResponseActivity>()
         .AfterActivity<AcceptCardDetails>()
         .When(_=>false);
     
      [WorkflowEvent(EventName.Signal)]
      public WorkflowAction OnSignal(WorkflowSignaledEvent @event)
      {
         if(@event.SignalName.Equals("WaitForBank")){
            return Jump.ToActivity<WaitForBankResponseActivity>();
         }
         if(@event.SignalName.Equals("AcceptCardDetails")){
            return Jump.ToActivity<AcceptCardDetails>();
         }
         
         return Ignore;
      }
   }
}
```

What we would like to achieve is to start the child workflow and run first activity from let's say **WaitForBankResponseActivity** or **AcceptCardDetails** based on a signal.

**Comment by gurmitteotia** [comment]
Hmm.. I was expecting this :)
There are two ways to deal with it:
1. Pass the hint about received signal to child workflow as input and use it in scheduling its activities.
```cs
[WorkflowDescription("1.0")]
public class OrderWorkflow : Workflow
{
   public OrderWorkflow()
   {  
      ScheduleActivity<CreateOrderActivity>()
         .When(_ => Input.resourceId != null)
         .OnCompletion(_ => Ignore);
      
      ScheduleChildWorkflow<ChargeCustomerWorkflow>().When(_ => Ignore)
       .WithInput(_=>new {WaitForBank=SignalReceived("WaitForBank"), AcceptCardDetails=SignalReceived("AcceptCardDetails")});
   }
   
    [SignalEvent]
    public Workflow WaitForBank()
         => Jump.ToChildWorkflow<ChargeCustomerWorkflow>()

   [SignalEvent]
    public Workflow AcceptCardDetails()
         => Jump.ToChildWorkflow<ChargeCustomerWorkflow>()
    
    private bool SignalReceived(string signalName)
           => AllSignalEvents.Any(e=>string.Equals(e.SignalName, signalName,StringComparer.OrdinalIgnoreCase); 
   }
}

[WorkflowDescription("1.0", Name = "charge-customer-workflow")]
public class ChargeCustomerWorkflow : Workflow
{
   public ChargeCustomerWorkflow()
   {
      ScheduleActivity<WaitForBankResponseActivity>().When(_=>Input.WaitForBank);
      ScheduleActivity<AcceptCardDetails>().When(_=>Input.AcceptCardDetails)
      ScheduleActivity<ChargeCustomer>()
         .AfterActivity<WaitForBankResponseActivity>()
         .AfterActivity<AcceptCardDetails>()
         .When(_=>false);
   }
 }

```

2. Pass the signal to child workflow as soon as it is started. But at the moment guflow intentionally ignore the child workflow started event and you can not implement this solution in current version. But I will expose it anyway in next release. After this change you can send the signal to child workflow as soon as it is started as shown below (I am just showing relevant code):
```cs
[WorkflowDescription("1.0")]
public class OrderWorkflow : Workflow
{
   public OrderWorkflow()
   {  
      ScheduleActivity<CreateOrderActivity>()
         .When(_ => Input.resourceId != null)
         .OnCompletion(_ => Ignore);
     
      ScheduleChildWorkflow<ChargeCustomerWorkflow>().When(_ => false)
       .OnStarted(e=>Signal("whatever").ToChildWorkflow<ChargeCustomerWorkflow>());
   }
}
```
I will prefer first approach if it solves your issue.

**Comment by gurmitteotia** [comment]
Is your issue resolved? I have also released the new version of Guflow where you can handle "OnStarted" event on child workflow to implement second approach.

**Comment by alexzm1** [comment]
Hi! We didn't got a chance to test this, we'll give an update in the next days, but theoretically this will solve our doubts.

**Comment by gurmitteotia** [comment]
In latest release you have the flexibility to implement the second solution. I'm closing this issue now. Please feel free to reopen it if issue persist?
