### ISSUE TITLE
Newtonsoft Version constaints

### ISSUE THREAD

**Issue by alexzm1** [gurmitteotia/guflow#42]
Hi!

Created this issue to ask if is it possible to have a Guflow's release which doesn't require the latest version of Newtonsoft? 

We have some of our internal dependencies (Nuget packages) which restricts Newtonsoft's version to be minor to **12.0.0**

Thanks!

**Comment by gurmitteotia** [comment]
It will be confusing to other users if I make a new release just by downgrading the Newtonsoft version. Can not your internal project have the dependency on Newtonsoft version =>12.0.0.0?
