### ISSUE TITLE
Workflow Hosting and Workflow Activity intermittently not working

### ISSUE THREAD

**Issue by alexzm1** [gurmitteotia/guflow#43]
We found some of our WorkflowHosting and ActivitiesHosting which suddenly stopped processing Activities or new Events in the WorkflowExecution after being running for a while, this seems to get fixed after we restart our apps, we're trying to gather more information about how to recreate the issue but by now wanted to create the issue in case we can gather more debugging information from the community about this this scenarios that can help to fix this issue

**Comment by gurmitteotia** [comment]
WorkflowHost or ActivityHost will not poll for new decisions/work if they are in "HostState.Faulted" state. Can you check HostStatus of "WorkflowHost/ActivityHost" when you end up in this situation?

WorkflowHost or ActivityHost can transition to faulted state on [unhandled exception](https://github.com/gurmitteotia/guflow/wiki/Error-handling).

**Comment by gurmitteotia** [comment]
Is it sorted for you now? I will prefer to look at this issue before picking up next feature.

**Comment by alexzm1** [comment]
Yeah! we sorted out this, we can close it, thanks!
