### ISSUE TITLE
Upgrade of AWSSDK dependencies

### ISSUE THREAD

**Issue by alexzm1** [gurmitteotia/guflow#44]
Can we update the AWSSDK dependencies we require for Guflow to the latest version? 
We got a mail from Amazon Web Service representatives asking us to upgrade our AWSSDK.Core libraries and AWSSDK.S3 libraries to 3.3.104.3 or higher to avoid an issue reported in below 

https://github.com/dotnet/corefx/issues/20296

Below is an abstract of the Notification we got from AWS support team:

One or more applications in your AWS account targets the .NET Standard runtime, and has used the AWS SDK for .NET to upload files to Amazon S3. The .NET Standard runtime has unexpected behavior in the underlying HttpClient library [1], which affects requests that timeout. Changes were made to AWSSDK.Core and AWSSDK.S3 packages that mitigate the effect of this behavior by retrying them. Please upgrade to one of the versions listed below (or higher).

Request timeouts could occur, for example, when applications saturate the network or use a slow network connection. Retries by the AWS SDK for .NET in such situations increase the resiliency of your applications, especially for multistep operations such as S3 multi-part uploads.

What do I need to do?

Navigate to your application’s folder or bundle and do the following:
1. Check for use of the .NET Standard HTTPClient library:
a. Check to see if the folder contains a *.runtimeconfig.json file. If it’s present, continue. If it’s not, stop.
b. Load the JSON file in an editor and check if the value for the “tfm” property starts with “netcoreapp”. If it’s present, continue. If it’s not, stop.
2. Check for use of AWSSDK.Core and/or AWSSDK.S3 packages:
a. Load the *.deps.json file in an editor.
b. Search under the libraries object for a reference to AWSDK.S3, which should look something like this (N.N.N.N stands for version number):
"AWSSDK.S3/ N.N.N.N ": {
"type": "package",
"serviceable": true,
"sha512": "….",
"path": "awssdk.s3/ N.N.N.N ",
"hashPath": "awssdk.s3. N.N.N.nupkg.sha512"
},
c. If AWSSDK.S3 is found, and the version number is lower than the version listed in this message, upgrade it. If not, stop.
d. Repeat steps 2a-2c for “AWSSDK.Core”.
3. Upgrade AWSSDK packages:
a. Upgrade the AWSSDK.Core NuGet package to 3.3.104.3 or higher [2].
b. Upgrade the AWSSDK.S3 NuGet package to version 3.3.110.4 or higher [3].

Note: These instructions apply to applications that use the standard .NET publish command.

Resources:
1. .NET Core behavior: https://github.com/dotnet/corefx/issues/20296
2. Latest AWSSDK.Core NuGet package: https://www.nuget.org/packages/AWSSDK.Core
3. Latest AWSSDK.S3 NuGet package: https://www.nuget.org/packages/AWSSDK.S3

**Comment by gurmitteotia** [comment]
Sure I will make a new release by upgrading the Guflow's dependencies: AWS SDKs and NewtonSoft.Json to latest versions.

**Comment by gurmitteotia** [comment]
Made a new release 1.3.9 with up to date dependencies.
